### ISSUE TITLE
Explanation for permissions

### ISSUE THREAD

**Issue by jpggithub** [pklinken/Earmouse#7]
Hi,
Why do Earmouse v1.2 need the READ_PHONE_STATE permission?

Why do Earmouse need INTERNET permission ?
Thank you

**Comment by pklinken** [comment]
The app uses the internet to acquire new modules through user interaction.
The phone state one I'm not sure about, i think my IDE added some by itself
but i will clear that up before a release milestone.
On May 4, 2016 2:13 AM, "jpg" <notifications@github.com> wrote:

Hi,
Why do Earmouse v1.2 need the READ_PHONE_STATE permission?

Why do Earmouse need INTERNET permission ?
Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/pklinken/Earmouse/issues/7>

**Comment by pklinken** [comment]
https://github.com/pklinken/Earmouse/commit/ea16ef6d249270d1ceb5d1647336b639f679145a
Only necessary permissions should remain now.
